# Generated by Django 4.2.6 on 2023-12-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searsh',
            new_name='Search',
        ),
    ]
