# Generated by Django 4.2.6 on 2023-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('build_name', models.CharField(max_length=10)),
            ],
        ),
    ]
