# Generated by Django 4.2.6 on 2023-10-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='vendor',
            field=models.CharField(default='default_vendor_name', max_length=10),
        ),
        migrations.AddField(
            model_name='switching',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
