# Generated by Django 4.2.6 on 2023-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_switching_vendor_switching_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
