# Generated by Django 4.2.6 on 2023-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_building_remove_switching_build_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switching',
            name='building',
        ),
        migrations.AddField(
            model_name='switching',
            name='build_name',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
