# Generated by Django 4.2.6 on 2023-10-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_switching_building_switching_build_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switching',
            name='build_name',
        ),
    ]
