# Generated by Django 4.2.6 on 2023-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_switching_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='building',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
