# Generated by Django 4.2.6 on 2023-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_switching_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='building',
            field=models.CharField(default='.', max_length=10),
        ),
    ]
