# Generated by Django 4.2.6 on 2023-10-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_switching_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='website',
            field=models.URLField(blank=True, max_length=15, null=True),
        ),
    ]
