# Generated by Django 4.2.6 on 2023-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_switching_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='vendor',
            field=models.CharField(default='default_vendor_name', max_length=15),
        ),
        migrations.AlterField(
            model_name='switching',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
