# Generated by Django 4.2.6 on 2023-10-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_switching_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='building',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.building'),
        ),
    ]
