# Generated by Django 4.2.6 on 2023-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_switching_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='description',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
