# Generated by Django 4.2.6 on 2023-10-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_switching_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switching',
            old_name='description',
            new_name='descrip',
        ),
    ]
