# Generated by Django 4.2.6 on 2023-10-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_rename_description_switching_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switching',
            name='descrip',
        ),
    ]
