# Generated by Django 4.2.6 on 2023-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_remove_switching_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='description',
            field=models.CharField(default='non', max_length=30, null=True),
        ),
    ]
