# Generated by Django 4.2.6 on 2023-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_switching_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
