# Generated by Django 4.2.6 on 2023-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_blockedmac_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discrption', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockedMAC',
        ),
    ]
