# Generated by Django 4.2.6 on 2023-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_vlan_discrption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='vendor',
            field=models.CharField(default='default_vendor_name', max_length=50),
        ),
    ]
