# Generated by Django 4.2.6 on 2023-11-19 11:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_alter_switching_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacAddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid MAC address format.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('type', models.CharField(max_length=50)),
                ('ports', models.CharField(max_length=100)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.switching')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vlan')),
            ],
        ),
    ]
