# Generated by Django 4.2.6 on 2023-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_macaddresstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaddresstable',
            name='mac_address',
            field=models.CharField(max_length=50),
        ),
    ]
