# Generated by Django 4.2.6 on 2023-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_alter_macaddresstable_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='mac_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MacAddressTable',
        ),
    ]
