# Generated by Django 4.2.6 on 2023-11-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_remove_switching_mac_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='backup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
