# Generated by Django 4.2.6 on 2023-11-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_switching_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='new_backup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
