# Generated by Django 4.2.6 on 2023-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_switching_new_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='switching',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='DOWN', max_length=4),
        ),
    ]
