# Generated by Django 4.2.6 on 2023-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_switching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switching',
            name='status',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], default='DOWN', max_length=4),
        ),
    ]
