# Generated by Django 4.2.6 on 2023-12-07 08:41

import cidrfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_switching_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='ip_range',
            field=cidrfield.models.IPNetworkField(default='192.168.20.0', unique=True),
        ),
    ]
