# Generated by Django 4.2.6 on 2023-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_remove_building_ip_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='ip_range',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
