# Generated by Django 4.2.6 on 2023-12-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0048_switching_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('human_name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('vendor', models.CharField(default='default_vendor_name', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.building')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vlan')),
            ],
        ),
    ]
