# Generated by Django 4.2.6 on 2023-12-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0002_remove_accesspoint_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='none', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acsess_point.building'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acsess_point.vlan'),
        ),
    ]
