# Generated by Django 4.2.6 on 2023-12-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_switching_description'),
        ('acsess_point', '0003_building_vlan_alter_accesspoint_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.1', unique=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.building'),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vlan'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Vlan',
        ),
    ]
