# Generated by Django 4.2.6 on 2023-12-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0004_accesspoint_ip_address_alter_accesspoint_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
