# Generated by Django 4.2.6 on 2023-12-07 08:29

import cidrfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0006_ipadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipadress',
            name='ip_range',
            field=cidrfield.models.IPNetworkField(unique=True),
        ),
    ]
