# Generated by Django 4.2.6 on 2023-12-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0007_alter_ipadress_ip_range'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAdress',
        ),
    ]
