# Generated by Django 4.2.6 on 2023-12-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0009_ipadress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpAdress',
        ),
    ]
