# Generated by Django 4.2.6 on 2023-12-07 08:57

import cidrfield.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_remove_building_ip_range'),
        ('acsess_point', '0010_delete_ipadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', cidrfield.models.IPNetworkField(unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.building')),
            ],
        ),
    ]
