# Generated by Django 4.2.6 on 2023-12-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0013_remove_ipadress_access_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadress',
            name='access_point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acsess_point.accesspoint'),
        ),
    ]
