# Generated by Django 4.2.6 on 2023-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0015_remove_ipadress_access_point_alter_ipadress_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspoint',
            name='admin_password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='admin_user',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='mac_address',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='wifi_password',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
