# Generated by Django 4.2.6 on 2023-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0020_accesspoint_real_port_accesspoint_switch_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='real_port',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accesspoint',
            name='switch_ip',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
