# Generated by Django 4.2.6 on 2023-12-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0022_alter_accesspoint_real_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoint',
            name='switch_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
