# Generated by Django 4.2.6 on 2023-12-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_point', '0026_alter_accesspoint_real_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspoint',
            name='real_port',
        ),
        migrations.RemoveField(
            model_name='accesspoint',
            name='switch_ip',
        ),
    ]
