# Generated by Django 4.2.6 on 2023-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloced_Mac_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=25, unique=True)),
                ('vlan', models.CharField(max_length=25)),
                ('reason', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
