# Generated by Django 4.2.6 on 2023-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_mac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloced_mac_address',
            name='reason',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
