# Generated by Django 4.2.6 on 2023-11-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_mac', '0002_alter_bloced_mac_address_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloced_Mac_Address',
            new_name='Blocked_Mac_Address',
        ),
    ]
