# Generated by Django 4.2.6 on 2023-11-05 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_mac', '0004_alter_blocked_mac_address_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocked_mac_address',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
