# Generated by Django 4.2.6 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocked_mac', '0005_blocked_mac_address_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocked_mac_address',
            name='switch_ip',
            field=models.GenericIPAddressField(default='192.168.20.1'),
        ),
    ]
